import Head from "next/head";
import Home from "../Components/Home";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Bears Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
      <Home />
    </div>
  );
}
